### ISSUE TITLE
Refresh does not seem to work when editing child partials

### ISSUE THREAD

**Issue by sakamies** [pingyhq/pingy-cli#17] opened 2017-05-12 16:15 UTC
Not sure if I broke something or if this is a bug. I have ejs templates and scss setup. When I edit an scss or ejs partial that's included in the main files, the browser does no show the changes. The funky part is, that it doesn't even show the changes after a hard reload until I edit the main files.

Steps to reproduce:
- Start a new project
- Make a main.scss file
- Import a something.scss file in main.scss
- Edit something.scss and reload the browser

Same goes for ejs templates.

**Comment by davej** [comment] 2017-05-12 16:46
I can replicate the issue with EJS `includes`, I'll work on fixing that now.

I can't replicate the issue with *.scss imports though.

Tried the following:

> `main.scss`
```scss
@import '_body';
$heading-color: hotpink;

h1 {
  color: $heading-color;
}
```

> `_body.scss`
```scss
body {
  background: green;
}
```

Whenever I edit `_body.scss` then the browser reloads for me.  Please check for errors in the web browser console and let me know what version of node + OS you are using.

**Comment by davej** [comment] 2017-05-12 17:49
Fixed in ad90180 and released as `v0.6.6`.

Please let me know if your still having issues with `v0.6.6` of Pingy CLI.

**Closed by davej** 2017-05-12 17:49 UTC
Labels: bug

**Comment by sakamies** [comment] 2017-05-15 14:30
Not sure what it was with my scss partials, could be I just imagined it because now I can't reproduce it any more. Everything seems to work now, thank you!

**Comment by davej** [comment] 2017-05-15 14:32
Cool, good to hear. EJS partials reloading too?

**Comment by sakamies** [comment] 2017-05-15 22:11
Yep. 👍

**Comment by filtercake** [comment] 2017-05-23 08:23
hi.

i have that problem with pug includes.

in `index.pug` i do `include components/pre-header.pug`.

it renders fine, but when I change and save `components/pre-header.pug`, the index file is not re-rendered. I need to save the index file to trigger the re-rendering.

am on 0.6.6, mac, node 7.3.0

is there maybe a way to force-watch the directory? there is an `exclusions` array in the `.pingy.json`, maybe `inclusions` exists too?

**Comment by davej** [comment] 2017-05-23 09:05
Yes this is a known issue. Dupe of #19. Should be fixed in the next version.

**Comment by filtercake** [comment] 2017-05-23 09:22
oh, apologies for the dupe, jumped on the first issue which seemed related :/

**Comment by davej** [comment] 2017-05-23 10:07
No probs. On holidays so falling behind on issues but could to have them lined up for when I'm back 🙂
