### ISSUE TITLE
Error: write after end

### ISSUE THREAD

**Issue by claimred** [pingyhq/pingy-cli#27] opened 2017-05-16 12:26 UTC
Hello

I am experiencing an error after maybe a minute or two of running pingy dev 

```
Serving at http://localhost:65208
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:439:15)
    at script (E:\project\node_modules\sendevent\index.js:97:16)
    at Timeout.close (E:\project\node_modules\sendevent\index.js:104:5)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout `(timers.js:207:5)
```

Any advice?

**Comment by davej** [comment] 2017-05-17 07:55
That's Odd. What OS and node version are you using?

**Comment by claimred** [comment] 2017-05-17 12:28
```
E:\>ver

Microsoft Windows [Version 10.0.15063]

E:\>node --version
v6.9.5
```

Should I update node?

**Comment by davej** [comment] 2017-05-18 10:44
It probably won't make a difference. Have you tried other browsers? It's possible that your browser is doing something strange with the open connection. I'm on holiday at the moment so it will be a few weeks before I can debug this properly.

Thanks for the bug report.

**Comment by claimred** [comment] 2017-05-18 13:37
> Have you tried other browsers?

Yeah, tried looking into it more thoroughly, seems random. Sometimes it crashes while idling in Chrome, or both Chrome and Edge/IE, or without any browser connected at all, after closing default browser that was automatically opened. It doesn't crash after editing js (boilerplate pingy generated scss/html/js files) but _sometimes_ it does after editing scss, maybe after a minute.

Can't quite pinpoint a clear test case unfortunately. :\

**Comment by davej** [comment] 2017-09-27 16:52
@claimred: Are you still experiencing this issue with Pingy 0.8.1? I'll close this issue but can reopen if the issue is still there.

**Comment by claimred** [comment] 2017-09-28 15:49
Yep, +-- @pingy/cli@0.8.1 and still the same `Error: write after end` thing

**Closed** 2017-09-29 18:47 UTC
Labels: bug

**Comment by davej** [comment] 2017-09-29 18:49
Ok, I believe I have fixed it now. Can you please try 0.8.2?

**Comment by claimred** [comment] 2017-09-30 10:07
@davej It works, thanks!

**Comment by davej** [comment] 2017-09-30 11:30
👍
